# Please note we are using Docker Compose version 3
version: '3'
services:
    # api: 
    client:
        build: ./client
        volumes:
            - ./client:/usr/src/app
        ports:
            - "8080:8080"
    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
            - "9001:9001"
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    influxdb:
        image: influxdb:alpine
        ports: 
            - "8086:8086"
        volumes:
            - ./influxdb-data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=probes
            - INFLUXDB_USER=influx
            - INFLUXDB_USER_PASSWORD=123456
    data-collector:
        image: streamsets/datacollector
        ports:
            - "18630:18630"
        links:
            - influxdb
    portainer:
        image: portainer/portainer
        command: --templates http://templates/templates.json
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer-data:/data
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:10001
        ports:
            - "10001:9000"

volumes:
  schemas:
    external: false
