# Please note we are using Docker Compose version 3
version: '3'
services:
    api: 
        build: ./api
        volumes:
            - ./api:/go/src/app
        ports: 
            - "8000:8000"
        links: 
            - redis
            - influx
        environment:
            - APP_ENV=development
    client:
        build: ./client
        volumes:
            - ./client:/usr/src/app
        ports:
            - "8080:8080"
    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
            - "9001:9001"
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data
        entrypoint: redis-server --appendonly yes
        restart: always
    influx:
        image: influxdb:alpine
        ports: 
            - "8086:8086"
        volumes:
            - ./influxdb-data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=tcc_data
            - INFLUXDB_USER=tcc
            - INFLUXDB_USER_PASSWORD=tcc_ufrj
    data-collector:
        build: ./sdc
        ports:
            - "18630:18630"
        volumes:
            - ./sdc/data:/data
        links:
            - influx
            - redis
volumes:
  schemas:
    external: false
