# Please note we are using Docker Compose version 3
version: '3'
services:
    # api: 
    client:
        build: ./client
        volumes:
            - ./client:/usr/src/app
        ports:
            - "8080:8080"
    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
            - "9001:9001"
    riak-coordinator:
        image: basho/riak-ts
        ports:
        - "8087:8087"
        - "8098:8098"
        environment:
        - CLUSTER_NAME=riakts
        labels:
        - "com.basho.riak.cluster.name=riakts"
        volumes:
        - schemas:/etc/riak/schemas
    riak-member:
        image: basho/riak-ts
        ports:
        - "8087"
        - "8098"
        labels:
        - "com.basho.riak.cluster.name=riakts"
        links:
        - riak-coordinator
        depends_on:
        - riak-coordinator
        environment:
        - CLUSTER_NAME=riakts
        - COORDINATOR_NODE=riak-coordinator

    portainer:
        image: portainer/portainer
        command: --templates http://templates/templates.json
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer-data:/data
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:10001
        ports:
            - "10001:9000"

volumes:
  schemas:
    external: false