# Please note we are using Docker Compose version 3
version: '3'
services:
    api: 
        build:
            context: ./api
            dockerfile: Dockerfile.production
        ports: 
            - "8000:8000"
        links: 
            - redis
            - influx
        environment:
            - APP_ENV=development
            
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.production
            args:
            - NODE_ENV="production"
            - API_HOST="http://localhost:8000"
            - API_WS_HOST="ws://localhost:8000"
            - INFLUX_HOST="http://localhost:8086"
        ports:
            - "8080:80"
        environment:
            - NODE_ENV="production"
            - API_HOST="http://localhost:8000"
            - API_WS_HOST="ws://localhost:8000"
            - INFLUX_HOST="http://localhost:8086"
    mosquitto:
        image: eclipse-mosquitto:1.6
        ports:
            - "1883:1883"
            - "9001:9001"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data
        entrypoint: redis-server --appendonly yes
        restart: always

    influx:
        image: influxdb:1.8
        ports: 
            - "8086:8086"
        volumes:
            - ./influxdb-data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=tcc_data
            - INFLUXDB_USER=tcc
            - INFLUXDB_USER_PASSWORD=tcc_ufrj

    data-collector:
        build: ./sdc
        ports:
            - "18630:18630"
        volumes:
            - ./sdc/data:/data
        links:
            - influx
            - redis

    portainer:
        image: portainer/portainer
        command: --templates http://templates/templates.json
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer-data:/data
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:10001
        ports:
            - "10001:9000"
volumes:
  schemas:
    external: false
