version: "2.1"
services:
  viewer:
    build: ./viewer
    command: bash -c "npm start"
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
  database: 
    image: mongo
    ports:
      - "27017:27017"

  # jobmanager:
  #   image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
  #   expose:
  #     - "6123"
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
    # environment:
    #   - JOB_MANAGER_RPC_ADDRESS=jobmanager

  # taskmanager:
  #   image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
  #   expose:
  #     - "6121"
  #     - "6122"
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   links:
  #     - "jobmanager:jobmanager"
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager
