apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: gcr.io/tcc-ufrj/client:v1
          name: client
          ports:
          - containerPort: 80
            name: client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: client