apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - sensein.tech
    - api.sensein.tech
    - sdc.sensein.tech
    - influx.sensein.tech
    secretName: sensein-letscrypt-tls
  rules:
  - host: sensein.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client
            port:
              number: 80
  - host: sdc.sensein.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sdc
            port:
              number: 18630
  - host: mqqt.sensein.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mqtt
            port:
              number: 1883
  - host: influx.sensein.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: influx
            port:
              number: 8086
  - host: api.sensein.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api
            port:
              number: 8000
