apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
          - name: mosquitto-storage
            mountPath: /mosquitto/data
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      volumes:
      - name: mosquitto-storage
        emptyDir: {}
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
  - name: mosquitto
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mosquitto-ws
    port: 9001
    protocol: TCP
    targetPort: 9001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    listener 1883
    allow_anonymous true
    protocol mqtt

    listener 9001
    protocol websockets