apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sdc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sdc
    spec:
      containers:
      - name: sdc
        image: streamsets/datacollector
        ports:
        - containerPort: 18630
        volumeMounts:
        - name: sdc-data-storage
          mountPath: /data
        lifecycle:
          postStart:
            exec:
              command: ["${SDC_DIST}/bin/streamsets", "stagelibs", "-install=streamsets-datacollector-redis-lib,streamsets-datacollector-influxdb_0_9-lib"]
      volumes:
      - name: sdc-data-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sdc
  labels:
    app: sdc
spec:
  selector:
    app: sdc
  ports:
  - name: sdc
    port: 18630
    protocol: TCP
    targetPort: 18630
  type: LoadBalancer
  loadBalancerIP: 35.198.46.103