name: client-ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create .env
        run: |
          touch ./client/.env
          {
            echo NODE_ENV="production"
            echo API_HOST="https://api.sensein.tech"
            echo INFLUX_HOST="https://influx.sensein.tech"
            echo API_WS_HOST="wss://api.sensein.tech"
            echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          } >> ./client/.env
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.production
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/tcc-client:latest
          cache-to: type=inline
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tcc-client:latest
